version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: two-tier-flask-app-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build: .
    container_name: two-tier-flask-app-flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_DB: flaskdb
    depends_on:
      - mysql
    volumes:
      - .:/app

volumes:
  mysql_data:

