apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod

spec:
  containers:
    - name: two-tier-app-ctr
      image: deepanshub9/flask-app:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "flaskuser"
        - name: MYSQL_PASSWORD
          value: "flaskpass"
        - name: MYSQL_DB
          value: "flaskdb"
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
